### ISSUE TITLE
Projeto incompleto

### ISSUE THREAD

**Issue by alan-chris** [Nelson-Afonso404/Fast-Tools#3]
Os botões de navegação superior não levam a lugar nenhum e os três cards direcionam para o mesmo link, apesar de serem diferentes

**Comment by Nelson-Afonso404** [comment]
> Os botões de navegação superior não levam a lugar nenhum e os três cards direcionam para o mesmo link, apesar de serem diferentes 

Ah eu sei, eu publiquei o projeto do zero e estou fazendo os commits a os poucos

**Comment by Nelson-Afonso404** [comment]
> Os botões de navegação superior não levam a lugar nenhum e os três cards direcionam para o mesmo link, apesar de serem diferentes 

Opa obrigado pela issue, o projeto está incompleto mesmo, é que eu comecei aqui no github do zero e estou fazendo os commits aos poucos
